In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np

In [5]:
arr = np.array(my_list)

In [6]:
arr

array([1, 2, 3])

In [7]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [17]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [18]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [22]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [6]:
np.random.rand(5)

array([0.62829345, 0.00354724, 0.47026812, 0.73272648, 0.25657172])

In [8]:
np.random.randn(2)

array([0.06355362, 1.72522686])

In [12]:
arr = np.arange(50)

In [8]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [9]:
ranarr = np.random.randint(0,50,10)

In [10]:
ranarr

array([ 2, 12,  3,  8, 20, 23,  9, 22, 36, 43])

In [14]:
arr.reshape(5,10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])